### PR TITLE
Fix macro hygiene

### PR DESCRIPTION
**Pull request by teohhanhui**
Reference: https://gist.github.com/Kestrer/8c05ebd4e0e9347eb05f265dfb7252e1

### CODE REVIEW

**Comment by alexjg** [comment]
Did you do all these by hand or do you have a linter doing them for you?

**Comment by teohhanhui** [comment]
Doing this by hand...

**Comment by teohhanhui** [comment]
This is still a draft because I'm only about halfway through... I'll continue after getting some sleep lol

**Comment by alexjg** [comment]
Ha, yeah get some sleep, you deserve it after staring at all those `::`s.

**Comment by teohhanhui** [comment]
I think one big thing I've missed is: https://docs.rs/quote/latest/quote/macro.quote.html#making-method-calls

e.g.

```rust
let inner = #inner_ty::hydrate(doc, obj, prop);
```

should be

```rust
let inner = <#inner_ty as ::autosurgeon::hydrate::Hydrate>::hydrate(
    doc,
    obj,
    prop,
);
```

**Pull request merged**
